scrape_configs:
  - job_name: 'dados-service'
    metrics_path: '/dados-service/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['service.127.0.0.1.xip.io:8080']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'tirada-service'
    metrics_path: '/dados-tirada-service/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['service.127.0.0.1.xip.io:8081']
    tls_config:
      insecure_skip_verify: true
